const express = require('express');
const auth = require('../middleware/auth.middleware');
const { validate } = require('../middleware/validation.middleware');
const { authLimiter } = require('../middleware/rateLimit.middleware');
const v = require('../validators');
const a = require('../controllers/auth.controller');
const c = require('../controllers/course.controller');
const l = require('../controllers/lesson.controller');
const e = require('../controllers/enrollment.controller');
const cm = require('../controllers/comment.controller');
const r = require('../controllers/rating.controller');
const p = require('../controllers/progress.controller');
const locked = require('../services/courseLock');
const router = express.Router();
const student = [auth.protect, auth.authorizeRoles('student')];
const instructor = [auth.protect, auth.authorizeRoles('instructor')];
const ids = (...names) => validate(v.params(...names), 'params');
const paging = validate(v.paging, 'query');
router.post('/auth/register', authLimiter, validate(v.register), a.register);
router.post('/auth/login', authLimiter, validate(v.login), a.login);
router.use(auth.optionalAuth);
router.get('/auth/me', auth.protect, a.me);
router.get('/categories', c.categories);
router.get('/instructor/courses', ...instructor, paging, c.mine);
router.get('/instructor/stats', ...instructor, c.stats);
router.get('/courses', validate(v.courseQuery, 'query'), c.list);
router.post('/courses', ...instructor, validate(v.createCourse), c.create);
router.get('/courses/:courseId', ids('courseId'), c.get);
router.patch('/courses/:courseId', ...instructor, ids('courseId'), validate(v.updateCourse), c.update);
router.delete('/courses/:courseId', ...instructor, ids('courseId'), locked(c.remove));
router.get('/courses/:courseId/lessons', ids('courseId'), l.list);
router.post('/courses/:courseId/lessons', ...instructor, ids('courseId'), validate(v.createLesson), l.create);
router.get('/courses/:courseId/lessons/:lessonId', ids('courseId', 'lessonId'), l.get);
router.patch('/courses/:courseId/lessons/:lessonId', ...instructor, ids('courseId', 'lessonId'), validate(v.updateLesson), l.update);
router.delete('/courses/:courseId/lessons/:lessonId', ...instructor, ids('courseId', 'lessonId'), l.remove);
router.post('/courses/:courseId/enroll', ...student, ids('courseId'), e.create);
router.delete('/courses/:courseId/enroll', ...student, ids('courseId'), locked(e.remove));
router.get('/courses/:courseId/enrollment-status', ...student, ids('courseId'), e.status);
router.get('/enrollments/me', ...student, paging, e.mine);
router.get('/courses/:courseId/progress', ...student, ids('courseId'), p.get);
router.patch('/lessons/:lessonId/progress', ...student, ids('lessonId'), validate(v.progress), p.update);
router.get('/lessons/:lessonId/comments', auth.protect, ids('lessonId'), paging, cm.list);
router.post('/lessons/:lessonId/comments', ...student, ids('lessonId'), validate(v.comment), cm.create);
router.patch('/comments/:commentId', ...student, ids('commentId'), validate(v.comment), cm.update);
router.delete('/comments/:commentId', ...student, ids('commentId'), cm.remove);
router.get('/courses/:courseId/ratings', ids('courseId'), paging, r.list);
router.post('/courses/:courseId/ratings', ...student, ids('courseId'), validate(v.rating), locked(r.create));
router.patch('/courses/:courseId/ratings/me', ...student, ids('courseId'), validate(v.rating), locked(r.update));
router.delete('/courses/:courseId/ratings/me', ...student, ids('courseId'), locked(r.remove));
module.exports = router;
